//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCONetDevTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerFileName {
            get {
                return ((string)(this["ServerFileName"]));
            }
            set {
                this["ServerFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalFilePathName {
            get {
                return ((string)(this["LocalFilePathName"]));
            }
            set {
                this["LocalFilePathName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S1Address {
            get {
                return ((string)(this["S1Address"]));
            }
            set {
                this["S1Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S2Address {
            get {
                return ((string)(this["S2Address"]));
            }
            set {
                this["S2Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S3Address {
            get {
                return ((string)(this["S3Address"]));
            }
            set {
                this["S3Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S4Address {
            get {
                return ((string)(this["S4Address"]));
            }
            set {
                this["S4Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S5Address {
            get {
                return ((string)(this["S5Address"]));
            }
            set {
                this["S5Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S1KeyPrefix {
            get {
                return ((string)(this["S1KeyPrefix"]));
            }
            set {
                this["S1KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S2KeyPrefix {
            get {
                return ((string)(this["S2KeyPrefix"]));
            }
            set {
                this["S2KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S3KeyPrefix {
            get {
                return ((string)(this["S3KeyPrefix"]));
            }
            set {
                this["S3KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S4KeyPrefix {
            get {
                return ((string)(this["S4KeyPrefix"]));
            }
            set {
                this["S4KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S5KeyPrefix {
            get {
                return ((string)(this["S5KeyPrefix"]));
            }
            set {
                this["S5KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S1Key {
            get {
                return ((string)(this["S1Key"]));
            }
            set {
                this["S1Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S2Key {
            get {
                return ((string)(this["S2Key"]));
            }
            set {
                this["S2Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S3Key {
            get {
                return ((string)(this["S3Key"]));
            }
            set {
                this["S3Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S4Key {
            get {
                return ((string)(this["S4Key"]));
            }
            set {
                this["S4Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S5Key {
            get {
                return ((string)(this["S5Key"]));
            }
            set {
                this["S5Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S1Value {
            get {
                return ((string)(this["S1Value"]));
            }
            set {
                this["S1Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S2Value {
            get {
                return ((string)(this["S2Value"]));
            }
            set {
                this["S2Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S3Value {
            get {
                return ((string)(this["S3Value"]));
            }
            set {
                this["S3Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S4Value {
            get {
                return ((string)(this["S4Value"]));
            }
            set {
                this["S4Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S5Value {
            get {
                return ((string)(this["S5Value"]));
            }
            set {
                this["S5Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S1Enabled {
            get {
                return ((bool)(this["S1Enabled"]));
            }
            set {
                this["S1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S2Enabled {
            get {
                return ((bool)(this["S2Enabled"]));
            }
            set {
                this["S2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S3Enabled {
            get {
                return ((bool)(this["S3Enabled"]));
            }
            set {
                this["S3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S4Enabled {
            get {
                return ((bool)(this["S4Enabled"]));
            }
            set {
                this["S4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S5Enabled {
            get {
                return ((bool)(this["S5Enabled"]));
            }
            set {
                this["S5Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TkFilterAddress {
            get {
                return ((string)(this["TkFilterAddress"]));
            }
            set {
                this["TkFilterAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkFilterAddressEn {
            get {
                return ((bool)(this["TkFilterAddressEn"]));
            }
            set {
                this["TkFilterAddressEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TkFilterKeyPrefix {
            get {
                return ((string)(this["TkFilterKeyPrefix"]));
            }
            set {
                this["TkFilterKeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkFilterKeyPrefixEn {
            get {
                return ((bool)(this["TkFilterKeyPrefixEn"]));
            }
            set {
                this["TkFilterKeyPrefixEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TkFilterKey {
            get {
                return ((string)(this["TkFilterKey"]));
            }
            set {
                this["TkFilterKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkFilterKeyEn {
            get {
                return ((bool)(this["TkFilterKeyEn"]));
            }
            set {
                this["TkFilterKeyEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TkFilterValue {
            get {
                return ((string)(this["TkFilterValue"]));
            }
            set {
                this["TkFilterValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkFilterValueEn {
            get {
                return ((bool)(this["TkFilterValueEn"]));
            }
            set {
                this["TkFilterValueEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkOvAddressEn {
            get {
                return ((bool)(this["TkOvAddressEn"]));
            }
            set {
                this["TkOvAddressEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkOvKeyPrefixEn {
            get {
                return ((bool)(this["TkOvKeyPrefixEn"]));
            }
            set {
                this["TkOvKeyPrefixEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkOvKeyEn {
            get {
                return ((bool)(this["TkOvKeyEn"]));
            }
            set {
                this["TkOvKeyEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TkOvValueEn {
            get {
                return ((bool)(this["TkOvValueEn"]));
            }
            set {
                this["TkOvValueEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BinFilePath {
            get {
                return ((string)(this["BinFilePath"]));
            }
            set {
                this["BinFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeProductInfoFile {
            get {
                return ((bool)(this["IncludeProductInfoFile"]));
            }
            set {
                this["IncludeProductInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeCanAddressFile {
            get {
                return ((bool)(this["IncludeCanAddressFile"]));
            }
            set {
                this["IncludeCanAddressFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCanAddressStatic {
            get {
                return ((bool)(this["IsCanAddressStatic"]));
            }
            set {
                this["IsCanAddressStatic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FlashVolumeBaseAddress {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlashVolumeBaseAddress"]));
            }
            set {
                this["FlashVolumeBaseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FlashVolumeSize {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlashVolumeSize"]));
            }
            set {
                this["FlashVolumeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelName {
            get {
                return ((string)(this["ModelName"]));
            }
            set {
                this["ModelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManufacturerName {
            get {
                return ((string)(this["ManufacturerName"]));
            }
            set {
                this["ManufacturerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HardwareRevision {
            get {
                return ((string)(this["HardwareRevision"]));
            }
            set {
                this["HardwareRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppFirmwareRevision {
            get {
                return ((string)(this["AppFirmwareRevision"]));
            }
            set {
                this["AppFirmwareRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BootloaderFirmwareRevision {
            get {
                return ((string)(this["BootloaderFirmwareRevision"]));
            }
            set {
                this["BootloaderFirmwareRevision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseIndexedOutputEnum {
            get {
                return ((string)(this["BaseIndexedOutputEnum"]));
            }
            set {
                this["BaseIndexedOutputEnum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaxIndexedOutputEnum {
            get {
                return ((string)(this["MaxIndexedOutputEnum"]));
            }
            set {
                this["MaxIndexedOutputEnum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string StaticCanAddress {
            get {
                return ((string)(this["StaticCanAddress"]));
            }
            set {
                this["StaticCanAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BinSaveToLocalFile {
            get {
                return ((bool)(this["BinSaveToLocalFile"]));
            }
            set {
                this["BinSaveToLocalFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BinSaveToFlashFileSystem {
            get {
                return ((bool)(this["BinSaveToFlashFileSystem"]));
            }
            set {
                this["BinSaveToFlashFileSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeTimeLogicFile {
            get {
                return ((bool)(this["IncludeTimeLogicFile"]));
            }
            set {
                this["IncludeTimeLogicFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string TimeLogicReservedSpace {
            get {
                return ((string)(this["TimeLogicReservedSpace"]));
            }
            set {
                this["TimeLogicReservedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeLogicImportFileName {
            get {
                return ((string)(this["TimeLogicImportFileName"]));
            }
            set {
                this["TimeLogicImportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectExpressionTemplateCollectionFileName {
            get {
                return ((string)(this["ProjectExpressionTemplateCollectionFileName"]));
            }
            set {
                this["ProjectExpressionTemplateCollectionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectProductAssemblyFileName {
            get {
                return ((string)(this["ProjectProductAssemblyFileName"]));
            }
            set {
                this["ProjectProductAssemblyFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLightEngineIds {
            get {
                return ((bool)(this["ShowLightEngineIds"]));
            }
            set {
                this["ShowLightEngineIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TimeLogicFileLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TimeLogicFileLocations"]));
            }
            set {
                this["TimeLogicFileLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TimeLogicFileReservedSpace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TimeLogicFileReservedSpace"]));
            }
            set {
                this["TimeLogicFileReservedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TimeLogicFileInclude {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TimeLogicFileInclude"]));
            }
            set {
                this["TimeLogicFileInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection GCCCodeCompilation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GCCCodeCompilation"]));
            }
            set {
                this["GCCCodeCompilation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64.0")]
        public string LeIconXScale {
            get {
                return ((string)(this["LeIconXScale"]));
            }
            set {
                this["LeIconXScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public string LeIconYScale {
            get {
                return ((string)(this["LeIconYScale"]));
            }
            set {
                this["LeIconYScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectExpressionCollectionFileName {
            get {
                return ((string)(this["ProjectExpressionCollectionFileName"]));
            }
            set {
                this["ProjectExpressionCollectionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EquationsFileNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EquationsFileNames"]));
            }
            set {
                this["EquationsFileNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EquationsFilePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EquationsFilePaths"]));
            }
            set {
                this["EquationsFilePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BytecodeInclude {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BytecodeInclude"]));
            }
            set {
                this["BytecodeInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BytecodeSaveToLocalFile {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BytecodeSaveToLocalFile"]));
            }
            set {
                this["BytecodeSaveToLocalFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileName"]));
            }
            set {
                this["MiscFlashFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileIsBin {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileIsBin"]));
            }
            set {
                this["MiscFlashFileIsBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileIsIncluded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileIsIncluded"]));
            }
            set {
                this["MiscFlashFileIsIncluded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileVolume {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileVolume"]));
            }
            set {
                this["MiscFlashFileVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileIsReservedSpace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileIsReservedSpace"]));
            }
            set {
                this["MiscFlashFileIsReservedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MiscFlashFileReservedSpace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MiscFlashFileReservedSpace"]));
            }
            set {
                this["MiscFlashFileReservedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeIconXOffset {
            get {
                return ((string)(this["LeIconXOffset"]));
            }
            set {
                this["LeIconXOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeIconYOffset {
            get {
                return ((string)(this["LeIconYOffset"]));
            }
            set {
                this["LeIconYOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S6Address {
            get {
                return ((string)(this["S6Address"]));
            }
            set {
                this["S6Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S7Address {
            get {
                return ((string)(this["S7Address"]));
            }
            set {
                this["S7Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S8Address {
            get {
                return ((string)(this["S8Address"]));
            }
            set {
                this["S8Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S9Address {
            get {
                return ((string)(this["S9Address"]));
            }
            set {
                this["S9Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S10Address {
            get {
                return ((string)(this["S10Address"]));
            }
            set {
                this["S10Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S6KeyPrefix {
            get {
                return ((string)(this["S6KeyPrefix"]));
            }
            set {
                this["S6KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S7KeyPrefix {
            get {
                return ((string)(this["S7KeyPrefix"]));
            }
            set {
                this["S7KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S8KeyPrefix {
            get {
                return ((string)(this["S8KeyPrefix"]));
            }
            set {
                this["S8KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S9KeyPrefix {
            get {
                return ((string)(this["S9KeyPrefix"]));
            }
            set {
                this["S9KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S10KeyPrefix {
            get {
                return ((string)(this["S10KeyPrefix"]));
            }
            set {
                this["S10KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S6Key {
            get {
                return ((string)(this["S6Key"]));
            }
            set {
                this["S6Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S7Key {
            get {
                return ((string)(this["S7Key"]));
            }
            set {
                this["S7Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S8Key {
            get {
                return ((string)(this["S8Key"]));
            }
            set {
                this["S8Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S9Key {
            get {
                return ((string)(this["S9Key"]));
            }
            set {
                this["S9Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S10Key {
            get {
                return ((string)(this["S10Key"]));
            }
            set {
                this["S10Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S6Value {
            get {
                return ((string)(this["S6Value"]));
            }
            set {
                this["S6Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S7Value {
            get {
                return ((string)(this["S7Value"]));
            }
            set {
                this["S7Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S8Value {
            get {
                return ((string)(this["S8Value"]));
            }
            set {
                this["S8Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S9Value {
            get {
                return ((string)(this["S9Value"]));
            }
            set {
                this["S9Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string S10Value {
            get {
                return ((string)(this["S10Value"]));
            }
            set {
                this["S10Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S6Enabled {
            get {
                return ((bool)(this["S6Enabled"]));
            }
            set {
                this["S6Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S7Enabled {
            get {
                return ((bool)(this["S7Enabled"]));
            }
            set {
                this["S7Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S8Enabled {
            get {
                return ((bool)(this["S8Enabled"]));
            }
            set {
                this["S8Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S9Enabled {
            get {
                return ((bool)(this["S9Enabled"]));
            }
            set {
                this["S9Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool S10Enabled {
            get {
                return ((bool)(this["S10Enabled"]));
            }
            set {
                this["S10Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_Address {
            get {
                return ((string)(this["BST_Address"]));
            }
            set {
                this["BST_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_KeyPrefix {
            get {
                return ((string)(this["BST_KeyPrefix"]));
            }
            set {
                this["BST_KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_Key {
            get {
                return ((string)(this["BST_Key"]));
            }
            set {
                this["BST_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_Value {
            get {
                return ((string)(this["BST_Value"]));
            }
            set {
                this["BST_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_PacketsPerMessage {
            get {
                return ((string)(this["BST_PacketsPerMessage"]));
            }
            set {
                this["BST_PacketsPerMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BST_MessagesPerSecond {
            get {
                return ((string)(this["BST_MessagesPerSecond"]));
            }
            set {
                this["BST_MessagesPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NPS_PingAllNodes {
            get {
                return ((bool)(this["NPS_PingAllNodes"]));
            }
            set {
                this["NPS_PingAllNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPS_Hours {
            get {
                return ((string)(this["NPS_Hours"]));
            }
            set {
                this["NPS_Hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPS_Minutes {
            get {
                return ((string)(this["NPS_Minutes"]));
            }
            set {
                this["NPS_Minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPS_Seconds {
            get {
                return ((string)(this["NPS_Seconds"]));
            }
            set {
                this["NPS_Seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPS_PingsPerNode {
            get {
                return ((string)(this["NPS_PingsPerNode"]));
            }
            set {
                this["NPS_PingsPerNode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NPS_TestForPeriod {
            get {
                return ((bool)(this["NPS_TestForPeriod"]));
            }
            set {
                this["NPS_TestForPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BST_UseDefaultToken {
            get {
                return ((bool)(this["BST_UseDefaultToken"]));
            }
            set {
                this["BST_UseDefaultToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LM_Messages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LM_Messages"]));
            }
            set {
                this["LM_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FWU_FilePath {
            get {
                return ((string)(this["FWU_FilePath"]));
            }
            set {
                this["FWU_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ODM_RetainOfflineDevices {
            get {
                return ((bool)(this["ODM_RetainOfflineDevices"]));
            }
            set {
                this["ODM_RetainOfflineDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ODM_SystemPowerState {
            get {
                return ((bool)(this["ODM_SystemPowerState"]));
            }
            set {
                this["ODM_SystemPowerState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TM_ShowExpiredStatusMessages {
            get {
                return ((bool)(this["TM_ShowExpiredStatusMessages"]));
            }
            set {
                this["TM_ShowExpiredStatusMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TM_ShowCurrentStatusMessages {
            get {
                return ((bool)(this["TM_ShowCurrentStatusMessages"]));
            }
            set {
                this["TM_ShowCurrentStatusMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TM_ShowEvents {
            get {
                return ((bool)(this["TM_ShowEvents"]));
            }
            set {
                this["TM_ShowEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_Address {
            get {
                return ((string)(this["TT_Address"]));
            }
            set {
                this["TT_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_KeyPrefix {
            get {
                return ((string)(this["TT_KeyPrefix"]));
            }
            set {
                this["TT_KeyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_Key {
            get {
                return ((string)(this["TT_Key"]));
            }
            set {
                this["TT_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_Value1 {
            get {
                return ((string)(this["TT_Value1"]));
            }
            set {
                this["TT_Value1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_Value2 {
            get {
                return ((string)(this["TT_Value2"]));
            }
            set {
                this["TT_Value2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TT_TokensPerSecond {
            get {
                return ((string)(this["TT_TokensPerSecond"]));
            }
            set {
                this["TT_TokensPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TransmitDelaymS {
            get {
                return ((int)(this["TransmitDelaymS"]));
            }
            set {
                this["TransmitDelaymS"] = value;
            }
        }
    }
}
